import json
import logging
from typing import Any

from pydantic import BaseModel, ValidationError

from ..models import ModelInput
from .base import ModelProviderAdapter


class MistralFunctionAdapter(ModelProviderAdapter):
    """Adapter for Mistral models using function calling in AWS Bedrock.

    This adapter handles:
    1. Building tool definitions in Mistral's function-calling format.
    2. Migrating the system prompt into the messages array.
    3. Enforcing Mistral's 8192 token ceiling.
    4. Validating tool-use responses with granular debug logging.
    """


    logger = logging.getLogger(f"{__name__}.MistralFunctionAdapter")

    @classmethod
    def build_tool(cls, output_model: type[BaseModel]) -> dict[str, Any]:
        """Build a tool definition in Mistral's function-calling format.

        Preserves any ``$defs`` block generated by Pydantic, as Mistral
        can resolve nested schema references.

        Args:
            output_model (type[BaseModel]): The Pydantic model to convert
                to a tool definition.

        Returns:
            dict[str, Any]: Tool definition dict with function name,
                description, and parameters.
        """

        cls.logger.debug(f"Building tool definition for model: {output_model.__name__}")

        schema = output_model.model_json_schema()
        parameters = {
            "type": "object",
            "properties": schema.get("properties", {}),
            "required": schema.get("required", []),
        }

        # Keep nested definitions if Pydantic generated them
        if "$defs" in schema:
            parameters["$defs"] = schema["$defs"]

        return {
            "type": "function",
            "function": {
                "name": output_model.__name__,
                "description": schema.get("description", ""),
                "parameters": parameters,
            },
        }

    @classmethod
    def prepare_model_input(cls, model_input: ModelInput, output_model: type[BaseModel] | None = None) -> ModelInput:
        """Prepare model input for Mistral function-calling models.

        Moves the system prompt into the messages array, caps
        ``max_tokens`` at 8192, and attaches a tool definition when
        an output model is provided.

        Args:
            model_input (ModelInput): The original model input.
            output_model (type[BaseModel] | None): Optional Pydantic
                model defining the expected output structure.

        Returns:
            ModelInput: Modified model input with Mistral-specific
                configurations applied.
        """

        cls.logger.debug("Preparing model input for Mistral")

        model_input.anthropic_version = None

        # --- THE SYSTEM PROMPT FIX ---
        # Mistral strictly expects the system prompt inside the messages array
        if model_input.system and isinstance(model_input.system, str):
            if not model_input.messages:
                model_input.messages = []

            # Prepend the system prompt to the messages list
            model_input.messages.insert(0, {"role": "system", "content": model_input.system})

            # Delete the top-level key so AWS doesn't throw the 'extra_forbidden' error
            model_input.system = None
        # -----------------------------

        # Enforce Mistral's token ceiling
        if model_input.max_tokens and model_input.max_tokens > 8192:
            model_input.max_tokens = 8192

        if output_model:
            cls.logger.debug(f"Adding tool definition for {output_model.__name__}")
            model_input.tools = [cls.build_tool(output_model)]
            model_input.tool_choice = "any"

        return model_input

    @classmethod
    def validate_result(cls, result: dict[str, Any], output_model: type[BaseModel]) -> BaseModel | None:
        """Validate and parse output from Mistral function-calling models.

        Performs granular checks on the response structure — finish
        reason, assistant role, tool call count, and tool name — with
        debug logging at each step to aid batch failure diagnosis.

        Args:
            result (dict[str, Any]): Raw model output from Mistral.
            output_model (type[BaseModel]): Pydantic model to validate
                against.

        Returns:
            BaseModel | None: Validated model instance, or None if any
                check fails.
        """

        cls.logger.debug(f"Validating result against {output_model.__name__} schema")

        # Check we have choices
        choices = result.get("choices", [])
        if not choices:
            cls.logger.debug("No expected 'choices' key in result.")
            return None

        choice = choices[0]

        # Check that we stopped on purpose
        finish_reason = choice.get("finish_reason", "")
        if finish_reason != "tool_calls":
            cls.logger.debug(
                f"Expected 'tool_calls' as finish_reason, got '{finish_reason}'."
            )
            return None

        # Check that the assistant returned a message
        message = choice.get("message", {})
        if message.get("role", "") != "assistant":
            cls.logger.debug("Did not get the expected 'assistant' role.")
            return None

        # Check that the assistant returned tool calls
        tools = message.get("tool_calls", [])
        if not tools:
            cls.logger.debug("No tool calls found in assistant message.")
            return None

        if len(tools) != 1:
            cls.logger.debug(
                f"Expected exactly 1 tool call, got {len(tools)}."
            )
            return None

        # Check tool name matches expected model
        function = tools[0].get("function", {})
        tool_name = function.get("name", "")
        if tool_name != output_model.__name__:
            cls.logger.debug(
                f"Wrong tool name in response, expected "
                f"'{output_model.__name__}' got '{tool_name}'."
            )
            return None

        # Parse and validate arguments
        try:
            arguments = function.get("arguments", "{}")
            parsed_arguments = json.loads(arguments)
        except json.JSONDecodeError:
            cls.logger.debug(
                f"Failed to parse function arguments as JSON: {arguments}"
            )
            return None

        try:
            validated_model = output_model(**parsed_arguments)
            cls.logger.debug("Validation successful.")
            return validated_model
        except ValidationError as e:
            cls.logger.debug(f"Validation failed: {e!s}")
            return None
