import logging
from typing import Any

from pydantic import BaseModel, ValidationError

from ..models import ModelInput
from .base import ModelProviderAdapter


class NovaAdapter(ModelProviderAdapter):
    """Adapter for Amazon Nova models using the Bedrock Converse API.

    This adapter handles:
    1. Building tool definitions in the Converse ``toolSpec`` format.
    2. Reshaping messages, system prompts, and token limits into
       Converse API JSON arrays.
    3. Inlining ``$defs`` to resolve Pydantic ``$ref`` pointers that
       Nova cannot follow.
    4. Validating ``toolUse`` responses from the Converse API.
    """

    logger = logging.getLogger(f"{__name__}.NovaAdapter")

    @classmethod
    def build_tool(cls, output_model: type[BaseModel]) -> dict[str, Any]:
        """Build a tool definition in the Converse API ``toolSpec`` format.

        Inlines any ``$defs`` generated by Pydantic and provides a
        fallback description if the model's schema has none, since the
        Converse API rejects empty description strings.

        Args:
            output_model (type[BaseModel]): The Pydantic model to convert
                to a tool definition.

        Returns:
            dict[str, Any]: A Converse API tool definition with
                ``toolSpec``, ``inputSchema``, and resolved properties.
        """

        cls.logger.debug(f"Building tool definition for model: {output_model.__name__}")

        schema = output_model.model_json_schema()
        properties = schema.get("properties", {})

        # Inline the $defs to prevent the "lazy pointer" issue we saw with OSS models
        if "$defs" in schema:
            for _, prop_val in properties.items():
                if prop_val.get("type") == "array" and "$ref" in prop_val.get("items", {}):
                    ref_name = prop_val["items"]["$ref"].split("/")[-1]
                    if ref_name in schema["$defs"]:
                        prop_val["items"] = schema["$defs"][ref_name]

        parameters = {
            "type": "object",
            "properties": properties,
            "required": schema.get("required", []),
        }

        # Converse API strictly rejects zero-length strings for descriptions.
        description = schema.get("description", "").strip()
        if not description:
            description = f"Extract structured data matching the {output_model.__name__} schema."

        # Converse API wraps tools inside a "toolSpec" and "inputSchema -> json"
        return {
            "toolSpec": {
                "name": output_model.__name__,
                "description": description,
                "inputSchema": {
                    "json": parameters
                }
            }
        }

    @classmethod
    def prepare_model_input(cls, model_input: ModelInput, output_model: type[BaseModel] | None = None) -> ModelInput:
        """Prepare model input for Amazon Nova via the Converse API.

        Reshapes the standard ``ModelInput`` into the Converse API
        format: messages become content-block arrays, the system prompt
        becomes a text array, ``max_tokens`` moves into
        ``inferenceConfig``, and tools are wrapped in ``toolConfig``.

        Args:
            model_input (ModelInput): The original model input.
            output_model (type[BaseModel] | None): Optional Pydantic
                model defining the expected output structure.

        Returns:
            ModelInput: Modified model input with Converse API fields
                populated and legacy fields nullified.
        """

        cls.logger.debug("Preparing model input for Amazon Nova")

        # Clean up legacy artifacts
        model_input.anthropic_version = None

        # 1. Reshape the User Messages into Converse JSONArrays
        if model_input.messages:
            for msg in model_input.messages:
                if isinstance(msg.get("content"), str):
                    msg["content"] = [{"text": msg["content"]}]

        # 2. Reshape the System Prompt into a Converse JSONArray
        if model_input.system and isinstance(model_input.system, str):
            model_input.system = [{"text": model_input.system}]

        # 3. Reshape max_tokens into inferenceConfig
        if model_input.max_tokens:
            model_input.inferenceConfig = {"maxTokens": model_input.max_tokens}
            model_input.max_tokens = None

        # 4. Reshape tools into toolConfig
        if output_model:
            cls.logger.debug(f"Adding tool definition for {output_model.__name__}")
            tool_config = {
                "tools": [cls.build_tool(output_model)],
                "toolChoice": {
                    "tool": {"name": output_model.__name__}
                }
            }
            # Dynamically attach the toolConfig and delete the legacy keys
            model_input.toolConfig = tool_config
            model_input.tools = None
            model_input.tool_choice = None

        return model_input

    @classmethod
    def validate_result(cls, result: dict[str, Any], output_model: type[BaseModel]) -> BaseModel | None:
        """Validate and parse output from Amazon Nova's Converse API.

        Searches the response content blocks for a ``toolUse`` entry
        and validates its input against the provided Pydantic model.

        Args:
            result (dict[str, Any]): Raw model output from the Converse
                API.
            output_model (type[BaseModel]): Pydantic model to validate
                against.

        Returns:
            BaseModel | None: Validated model instance, or None if no
                ``toolUse`` block was found or validation fails.
        """

        cls.logger.debug(f"Validating result against {output_model.__name__} schema")

        # Converse API returns data in: output -> message -> content -> toolUse
        output = result.get("output", {})
        message = output.get("message", {})
        content_blocks = message.get("content", [])

        for block in content_blocks:
            if "toolUse" in block:
                try:
                    return output_model(**block["toolUse"]["input"])
                except ValidationError as e:
                    cls.logger.debug(f"Validation failed: {e!s}")
                    return None

        cls.logger.debug("Result contains no toolUse. The model hallucinated text.")
        return None
